DEBUG:root:Started application on port 9000
INFO:tornado.access:200 GET /get_winner_companies (::1) 288.15ms
DEBUG:root:Started application on port 9000
INFO:tornado.access:200 GET /get_winner_companies (::1) 225.29ms
DEBUG:root:Started application on port 9000
INFO:tornado.access:200 GET /get_winner_companies (::1) 134.95ms
DEBUG:root:Started application on port 9000
INFO:tornado.access:200 GET /get_instituicoes (::1) 3.51ms
DEBUG:root:Started application on port 9000
ERROR:tornado.application:Uncaught exception GET /get_instituicoes (::1)
HTTPServerRequest(protocol='http', host='localhost:9000', method='GET', uri='/get_instituicoes', version='HTTP/1.1', remote_ip='::1', headers={'Content-Type': 'application/json', 'Authorization': 'Bearer generate_password', 'Host': 'localhost:9000'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1469, in _execute
    result = yield result
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 270, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3.5/types.py", line 243, in wrapped
    coro = func(*args, **kwargs)
  File "/media/daniel/Dados/Daniel Documentos/Unb/5 Semestre/Projeto 2/Git/grupo 1/handlers/InstituicaoHandler.py", line 16, in get
    return cursor.next_object()
AttributeError: 'Future' object has no attribute 'next_object'
ERROR:tornado.access:500 GET /get_instituicoes (::1) 13.50ms
DEBUG:root:Started application on port 9000
ERROR:tornado.application:Uncaught exception GET /get_instituicoes (::1)
HTTPServerRequest(protocol='http', host='localhost:9000', method='GET', uri='/get_instituicoes', version='HTTP/1.1', remote_ip='::1', headers={'Content-Type': 'application/json', 'Authorization': 'Bearer generate_password', 'Host': 'localhost:9000'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1469, in _execute
    result = yield result
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/media/daniel/Dados/Daniel Documentos/Unb/5 Semestre/Projeto 2/Git/grupo 1/handlers/InstituicaoHandler.py", line 16, in get
    yield cursor.fetch_next
AttributeError: 'Future' object has no attribute 'fetch_next'
ERROR:tornado.access:500 GET /get_instituicoes (::1) 5.29ms
DEBUG:root:Started application on port 9000
ERROR:tornado.application:Uncaught exception GET /get_instituicoes (::1)
HTTPServerRequest(protocol='http', host='localhost:9000', method='GET', uri='/get_instituicoes', version='HTTP/1.1', remote_ip='::1', headers={'Content-Type': 'application/json', 'Authorization': 'Bearer generate_password', 'Host': 'localhost:9000'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1469, in _execute
    result = yield result
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/media/daniel/Dados/Daniel Documentos/Unb/5 Semestre/Projeto 2/Git/grupo 1/handlers/InstituicaoHandler.py", line 16, in get
    finished = yield cursor.fetch_next
AttributeError: 'Future' object has no attribute 'fetch_next'
ERROR:tornado.access:500 GET /get_instituicoes (::1) 6.13ms
DEBUG:root:Started application on port 9000
ERROR:tornado.application:Uncaught exception GET /get_instituicoes (::1)
HTTPServerRequest(protocol='http', host='localhost:9000', method='GET', uri='/get_instituicoes', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:9000', 'Content-Type': 'application/json', 'Authorization': 'Bearer generate_password'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1469, in _execute
    result = yield result
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/media/daniel/Dados/Daniel Documentos/Unb/5 Semestre/Projeto 2/Git/grupo 1/handlers/InstituicaoHandler.py", line 16, in get
    while (yield cursor.fetch_next):
AttributeError: 'Future' object has no attribute 'fetch_next'
ERROR:tornado.access:500 GET /get_instituicoes (::1) 14.99ms
DEBUG:root:Started application on port 9000
ERROR:tornado.application:Uncaught exception GET /get_instituicoes (::1)
HTTPServerRequest(protocol='http', host='localhost:9000', method='GET', uri='/get_instituicoes', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:9000', 'Authorization': 'Bearer generate_password', 'Content-Type': 'application/json'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1469, in _execute
    result = yield result
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/media/daniel/Dados/Daniel Documentos/Unb/5 Semestre/Projeto 2/Git/grupo 1/handlers/InstituicaoHandler.py", line 17, in get
    while (yield cursor.fetch_next):
AttributeError: 'list' object has no attribute 'fetch_next'
ERROR:tornado.access:500 GET /get_instituicoes (::1) 4.97ms
DEBUG:root:Started application on port 9000
INFO:tornado.access:200 GET /get_instituicoes (::1) 2.41ms
DEBUG:root:Started application on port 9000
INFO:tornado.access:200 GET /get_instituicoes (::1) 2.41ms
DEBUG:root:Started application on port 9000
INFO:tornado.access:200 GET /get_instituicoes (::1) 12.22ms
